remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Karan Vij"
description: "Engineering Leader & Solution Architect | 19+ Years Delivering Enterprise Web & Mobile Applications"
